### ISSUE TITLE
Questions regarding the approach

### ISSUE THREAD

**Issue by IoannisDadiotis** [Gepetto/constraints-as-terminations#1]
Hi,
First of all congrats for your approach and for open-sourcing. I was wondering if you could provide some info regarding the following questions I have:
1. Why do you multiply the rewards with (1-dones) in the following line? To my understanding the rewards of each step have been downscaled already at the `solo_terrain.py` in the code [here](https://github.com/Gepetto/constraints-as-terminations/blob/fb93bee4c4c00cc6de46b12340a4fa2ed5bb4135/tasks/solo_terrain.py#L711).
https://github.com/Gepetto/constraints-as-terminations/blob/fb93bee4c4c00cc6de46b12340a4fa2ed5bb4135/utils/cat_common.py#L90-L92
2. I was wondering what is the resulted ppo algorithm after your modifications. Nominal ppo usually looks like this:

`for env_step = N-1 to 0 do:`
1.  $\delta_{t} = r_{t} + \gamma \cdot V_{t+1} \cdot (1 - p_t) - V_{t}$
2. $` \hat{A}_{t} = \delta_{t} + \gamma \cdot \lambda \cdot \hat{A}_{t+1} \cdot (1 - p_t)`$
3. $`returns =  \hat{A}_{t} + V_{t}`$

, where $p_t$ takes boolean values 1 or 0 depending whether the environment has terminated or not.

To my understanding your approach results in the following modified ppo version:
1.  $\delta_{t} = r_{t} \cdot \color{red}(1 - p_t)\color{black}  + \gamma \cdot V_{t+1} \cdot \color{red}(1 - p_t)\color{black} - V_{t}$
2. $` \hat{A}_{t} = \delta_{t} + \gamma \cdot \lambda \cdot \hat{A}_{t+1} \cdot \color{red}(1 - p_t)\color{black} `$
3. $`returns =  \hat{A}_{t} + V_{t}`$

, where $p_t$ takes float values between 0 and 1 depending on the constraint violation. Is this correct?

3. Many times the ppo algorithms implement a kind of bootstrapping for environments that have reached their max duration (timeout). This usually looks like this $r_{t} = r_{t} + \gamma \cdot V_{t}$. Did you include such kind of terminations in your approach? In order to include them should the term $\gamma \cdot V_{t}$ be downscaled with $(1-p_t)$ as well?

5. Your modifications in ppo still do not exclude the possibility of having naive terminations (environment resets), right? There may be some cases where recovering from constraints is impossible and thus resuming stepping the env is just loss of time. E.g. we may want to reset the env if the robot has turned upside-down. I guess in this case there should be a kind of distinguish in the code between $p_t = 1$ because of recoverable or not constraint.

Thank you in advance
Ioannis

**Comment by elliotchanesane31** [comment]
Hi , thank you for your interest in our work, I am so sorry for the late reply !

1. I agree that we should not multiply by (1-dones) here. It doesn't seem to really matter though, as self.current_rewards is used only for logging purposes.
2. You are correct, CaT simply modifies the discount factor in the RL algorithm. We just modified the rl_games implementation of ppo to handle float dones values.
3. We probably didn't handle environment timeouts well in our code, but you are right: V_t should be downscaled with (1-p_t)
4. Indeed, our approach still handles regular environment resets. In fact, we do reset the environment when the robot is upside-down in our experiments:
https://github.com/Gepetto/constraints-as-terminations/blob/fb93bee4c4c00cc6de46b12340a4fa2ed5bb4135/tasks/solo_terrain.py#L920
cstr_upsidedown is a tensor of booleans. In combination with max_p=1, it results in p_t=1 if the robot has turned upside-down. When this occurs, the environment is reset:
https://github.com/Gepetto/constraints-as-terminations/blob/fb93bee4c4c00cc6de46b12340a4fa2ed5bb4135/tasks/solo_terrain.py#L946

Please don't hesitate to ask any further questions !
Elliot

**Comment by IoannisDadiotis** [comment]
Clear, thanks a lot
